name: Build and Deploy iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Verify Node.js and npm versions
      run: |
        node -v
        npm -v

    - name: List project files
      run: ls -la

    - name: Install dependencies (npm install instead of npm ci)
      run: npm install  # Essayer npm install au lieu de npm ci pour contourner l'erreur

    - name: Install Capacitor iOS dependencies
      run: |
        npm install @capacitor/ios
        npx cap add ios

    - name: Sync iOS project
      run: npx cap sync ios

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install

    - name: Build iOS app
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath build/App.xcarchive archive

    - name: Export IPA
      run: |
        cd ios/App
        xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: ios/App/build/*.ipa
